services:
  angular-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true